# Generated by Django 4.2.10 on 2025-07-17 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_id', models.CharField(max_length=255)),
                ('component_type', models.CharField(max_length=255)),
                ('data', models.JSONField(default=dict)),
                ('position_x', models.FloatField(default=0)),
                ('position_y', models.FloatField(default=0)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='workflows.workflow')),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='名称')),
                ('type', models.CharField(choices=[('llm', '语言模型'), ('chat_model', '对话模型'), ('embedding', '嵌入'), ('vector_store', '向量存储'), ('prompt', '提示词'), ('memory', '记忆'), ('chain', '链'), ('agent', '代理'), ('tool', '工具'), ('output_parser', '输出解析器'), ('document_loader', '文档加载器'), ('text_splitter', '文本分割器'), ('retriever', '检索器'), ('utility', '工具')], max_length=50, verbose_name='类型')),
                ('category', models.CharField(choices=[('language_models', '语言模型'), ('memory', '记忆'), ('chains', '链'), ('agents', '代理'), ('tools', '工具'), ('document_loders', '文档加载器'), ('vector_stores', '向量存储'), ('text_splitters', '文本分割器'), ('retrievers', '检索器'), ('embeddings', '嵌入'), ('prompts', '提示词'), ('output_parsers', '输出解析器'), ('utilities', '工具')], max_length=50, verbose_name='类别')),
                ('description', models.TextField(blank=True, verbose_name='描述')),
                ('icon', models.CharField(blank=True, max_length=255, null=True, verbose_name='图标')),
                ('version', models.CharField(default='1.0.0', max_length=20, verbose_name='版本')),
                ('input_schema', models.JSONField(blank=True, default=list, verbose_name='输入定义')),
                ('output_schema', models.JSONField(blank=True, default=list, verbose_name='输出定义')),
                ('params_schema', models.JSONField(blank=True, default=dict, verbose_name='参数定义')),
                ('class_path', models.CharField(help_text='组件类的导入路径，例如“components.implementations.llms.gemini.GeminiComponent”', max_length=255, verbose_name='类路径')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '组件',
                'verbose_name_plural': '组件',
                'indexes': [models.Index(fields=['type', 'category'], name='components__type_b093a6_idx')],
                'unique_together': {('name', 'type')},
            },
        ),
    ]
